enable: true
botToken: 5765557544:AAH601OuRn1yALdKQtweFCwGsLGjFIOKRuU
chats:
  - -913230405
admins:
  - 745877010
serverStartMessage: "✅Сервер запущен."
serverStopMessage: "⛔️Сервер выключен."
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logPlayerDeath: true
logPlayerAsleep: false
minecraftFormat: "%reply%(§l§d%chat%§r) §6§l%username%§r:§l§6%type%§r %message%§r"
replyToMessageFormat: "(§l§d%chat%§r) §a§o>§l%type%§r§a§o %message% - %username%§r\n"

telegramFormat: "<b>%username%</b>: %message%"
silentMessages: false
strings:
  online: "<b>Онлайн</b>"
  nobodyOnline: "Никого"
  joined: "<b>%username%</b> присоединился."
  left: "<b>%username%</b> вышел."
  advancementDone: "<b>%player%</b> получил достижение «%advancement%»!"

  photo: " [изображение]"
  audio: " [аудио: %filename%]"
  document: " [%filename%]"
  sticker: " [стикер %emoji%]"
  video: " [видео %filename%]"
  videoNote: " [видеосообщение %duration%s]"
  voice: " [голосовое сообщение %duration%s]"
  poll: " [опрос: %question%]"

  commandRunning: "Выполняем команду <code>%command%</code>..."
  commandResultLine: "\n<pre>%result%</pre>"

  advancement:
    "story/root": "Minecraft"
    "story/mine_stone": "Каменный век"
    "story/upgrade_tools": "Обновка!"
    "story/smelt_iron": "Куй железо..."
    "story/obtain_armor": "Дресс-код"
    "story/lava_bucket": "Горячая штучка"
    "story/iron_tools": "И кирка без дела ржавеет"
    "story/deflect_arrow": "Не дождётесь!"
    "story/form_obsidian": "Две стихии"
    "story/mine_diamond": "Алмазы!"
    "story/enter_the_nether": "Огненные недра"
    "story/shiny_gear": "Осыпь меня алмазами"
    "story/enchant_item": "Чародей"
    "story/cure_zombie_villager": "Доктор для зомби"
    "story/follow_ender_eye": "Недреманное око"
    "story/enter_the_end": "Конец?"

    "nether/root": "Незер"
    "nether/return_to_sender": "Вернуть отправителю"
    "nether/find_bastion": "Наф-наф тут больше не живёт"
    "nether/obtain_ancient_debris": "Осколки прошлого"
    "nether/fast_travel": "Кротовая нора"
    "nether/find_fortress": "Чертоги страха"
    "nether/obtain_crying_obsidian": "Обсидиановы слёзы"
    "nether/distract_piglin": "Бранзулетка"
    "nether/ride_strider": "Ты неси меня по лаве"
    "nether/ride_strider_in_overworld_lava": "Совсем как дома"
    "nether/uneasy_alliance": "Война миров"
    "nether/loot_bastion": "Было ваше — стало наше!"
    "nether/use_lodestone": "Путеводный камень"
    "nether/netherite_armor": "Ладные доспехи"
    "nether/get_wither_skull": "Бедный Йорик!"
    "nether/obtain_blaze_rod": "В полымя"
    "nether/charge_respawn_anchor": "Ларец Кощея"
    "nether/explore_nether": "Горящий тур"
    "nether/brew_potion": "Местный зельевар"
    "nether/summon_wither": "Чудо-юдо"
    "nether/all_potions": "Энергетический коктейль"
    "nether/create_beacon": "Желанный свет"
    "nether/all_effects": "Невозможное возможно!"
    "nether/create_full_beacon": "Маяковский"

    "end/root": "Край"
    "end/kill_dragon": "Освободите Край"
    "end/dragon_egg": "Новое поколение"
    "end/enter_end_gateway": "Идеальный побег"
    "end/respawn_dragon": "Дежавю"
    "end/dragon_breath": "Освежи дыхание"
    "end/find_end_city": "Будь как дома, путник"
    "end/elytra": "Где твои крылья?"
    "end/levitate": "Прекрасный вид!"

    "adventure/root": "Приключения"
    "adventure/voluntary_exile": "Добровольное изгнание"
    "adventure/kill_a_mob": "Охотник на монстров"
    "adventure/trade": "Не отходя от кассы!"
    "adventure/honey_block_slide": "Замёдленное падение"
    "adventure/ol_betsy": "Самострел"
    "adventure/sleep_in_bed": "Спи, моя радость, усни"
    "adventure/hero_of_the_village": "Герой деревни"
    "adventure/throw_trident": "Попасть впросак"
    "adventure/shoot_arrow": "Точно в цель"
    "adventure/kill_all_mobs": "Зверобой"
    "adventure/totem_of_undying": "Свет в конце тоннеля"
    "adventure/summon_iron_golem": "Три закона големотехники"
    "adventure/arbalistic": "Арбаллистика"
    "adventure/two_birds_one_arrow": "Двух птиц одним выстрелом"
    "adventure/whos_the_pillager_now": "И кто тут теперь разбойник?"
    "adventure/adventuring_time": "Время приключений"
    "adventure/very_very_frightening": "Грянул майский гром"
    "adventure/sniper_duel": "Снайперская дуэль"
    "adventure/bullseye": "В яблочко!"
    "adventure/avoid_vibration": "мыш (кродеться)"
    "adventure/walk_on_powder_snow_with_leather_boots": "Прыткий как заяц"
    "adventure/play_jukebox_in_meadows": "Играй, гармония!"
    "adventure/kill_mob_near_sculk_catalyst": "Оно живое"
    "adventure/fall_from_world_height": "Пещеры и скалы"
    "adventure/trade_at_world_height": "Звёздный торговец"

    "husbandry/root": "Сельское хозяйство"
    "husbandry/breed_an_animal": "Романтический ужин"
    "husbandry/tame_an_animal": "Друг человека"
    "husbandry/complete_catalogue": "Полный котолог"
    "husbandry/plant_seed": "Поле чудес"
    "husbandry/safely_harvest_honey": "Пора подкрепиться"
    "husbandry/silk_touch_nest": "Полосатый груз"
    "husbandry/fishy_business": "На крючке"
    "husbandry/bred_all_animals": "Счастливый фермер"
    "husbandry/balanced_diet": "Робин-Бобин"
    "husbandry/obtain_netherite_hoe": "Заявка на победу"
    "husbandry/tactical_fishing": "Рыбацкая хитрость"
    "husbandry/tadpole_in_a_bucket": "Почётный пассажир"
    "husbandry/leash_all_frog_variants": "Кто шагает дружно в ряд?"
    "husbandry/froglights": "Перекрёсток семи болот"
    "husbandry/allay_deliver_item_to_player": "Просто так!"
    "husbandry/allay_deliver_cake_to_note_block": "Только раз в году!"
    "husbandry/ride_a_boat_with_a_goat": "Волк, коза и капуста"

commands:
  time: "time"
  online: "online"
  chat_id: "chat_id"
  cmd: "cmd"
