enable: true
botToken: 123456:abcdef
chats: []
serverStartMessage: "Server started."
serverStopMessage: "Server stopped."
logJoinLeave: true
logFromMCtoTG: true
logFromTGtoMC: true
logPlayerDeath: true
logPlayerAsleep: false
minecraftFormat: "%reply%(§l§d%chat%§r) §6§l%username%§r:§l§6%type%§r %message%§r"
replyToMessageFormat: "(§l§d%chat%§r) §a§o>§l%type%§r§a§o %message%§r - §6%username%§r\n"

telegramFormat: "<b>%username%</b>: %message%"
silentMessages: false
strings:
  online: "<b>Online</b>"
  nobodyOnline: "<b>Nobody online...</b>"
  joined: "<i>%username%</i> joined."
  left: "<i>%username%</i> left."

  photo: " [photo]"
  audio: " [audio: %filename%]"
  document: " [document: %filename%]"
  sticker: " [sticker: %emoji%]"
  video: " [video: %filename%]"
  videoNote: " [video note: %duration%s]"
  voice: " [voice: %duration%s]"
  poll: " [poll: %question%]"
commands:
  time: "time"
  online: "online"
  chat_id: "chat_id"
