name: SpigotTGBridge
version: "0.20.1"
api-version: "1.15"
main: su.dromanov.tgchat.Plugin
description: Telegram <-> Minecraft communication plugin for Spigot.
commands:
  tgchat_reload:
    description: "Reload Spigot TG bridge plugin"
    usage: /<command>
